[".tmux/plugins/tpm"]
type = "archive"
url = "https://github.com/tmux-plugins/tpm/archive/refs/heads/master.zip"
exact = true
stripComponents = 1
refreshPeriod = "168h"

[".fonts/SourceCodePro/"]
type = "archive"
url = "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/SourceCodePro.zip"
exact = false
stripComponents = 0
refreshPeriod = "168h"

[".asdf"]
type = "archive"
url = "https://github.com/asdf-vm/asdf/archive/refs/heads/master.zip"
exact = false
stripComponents = 1
refreshPeriod = "168h"
