- name: github_copilot/o3-mini
  # edit_format: diff
  extra_params:
    max_tokens: 100000
    extra_headers:
      Editor-Version: Aider/0.84
      Copilot-Integration-Id: copilot-chat

- name: github_copilot/o4-mini
  # edit_format: diff
  extra_params:
    max_tokens: 100000
    extra_headers:
      Editor-Version: Aider/0.84
      Copilot-Integration-Id: copilot-chat

- name: github_copilot/gemini-2.5-pro
  edit_format: diff-fenced
  extra_params:
    max_tokens: 100000
    extra_headers:
      Editor-Version: Aider/0.84
      Copilot-Integration-Id: copilot-chat

- name: github_copilot/claude-sonnet-4
  # edit_format: diff
  extra_params:
    max_tokens: 100000
    extra_headers:
      Editor-Version: Aider/0.84
      Copilot-Integration-Id: copilot-chat

- name: github_copilot/gpt-4.1
  # edit_format: diff
  extra_params:
    max_tokens: 100000
    extra_headers:
      Editor-Version: Aider/0.84
      Copilot-Integration-Id: copilot-chat

- name: github_copilot/gpt-5-mini
  # edit_format: diff
  extra_params:
    max_tokens: 100000
    extra_headers:
      Editor-Version: Aider/0.84
      Copilot-Integration-Id: copilot-chat

- name: github_copilot/gpt-5
  # edit_format: diff
  extra_params:
    max_tokens: 100000
    extra_headers:
      Editor-Version: Aider/0.84
      Copilot-Integration-Id: copilot-chat
