- name: openai/o3-mini
  edit_format: diff
  max_chat_history_tokens: 80000
  extra_params:
    extra_headers:
      Editor-Version: Aider/0.84
      Copilot-Integration-Id: copilot-chat

- name: openai/o4-mini
  edit_format: diff
  max_chat_history_tokens: 80000
  extra_params:
    extra_headers:
      Editor-Version: Aider/0.84
      Copilot-Integration-Id: copilot-chat

- name: openai/gemini-2.5-pro
  edit_format: diff
  max_chat_history_tokens: 80000
  extra_params:
    extra_headers:
      Editor-Version: Aider/0.84
      Copilot-Integration-Id: copilot-chat

- name: openai/claude-sonnet-4
  edit_format: diff
  max_chat_history_tokens: 80000
  extra_params:
    extra_headers:
      Editor-Version: Aider/0.84
      Copilot-Integration-Id: copilot-chat

- name: openai/gpt-4.1
  edit_format: diff
  max_chat_history_tokens: 80000
  extra_params:
    extra_headers:
      Editor-Version: Aider/0.84
      Copilot-Integration-Id: copilot-chat
