[time_maps]
[time_maps.work]
monday = 6.5
tuesday = 6.5
wednesday = 6.5
thursday = 6.5
friday = 6.5
saturday = 0
sunday = 0

[time_maps.weekend]
monday = 0
tuesday = 0
wednesday = 0
thursday = 0
friday = 0
saturday = 3
sunday = 3

[time_maps.extra]
monday = 1
tuesday = 1
wednesday = 1
thursday = 1
friday = 1
saturday = 2
sunday = 2
