import = [ # the theme
  "~/.config/alacritty/themes/themes/tomorrow_night.toml"
]

[env]
WINIT_X11_SCALE_FACTOR = "1." # fix scaling for X11
TERM = "xterm-256color"

[font] # font
size = 10.5

[font.bold]
family = "monospace"
style = "Bold"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

[font.italic]
family = "monospace"
style = "Italic"

[font.normal]
family = "monospace"
style = "Regular"
